name: ci

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        if: steps.cache.outputs.cache-hit == 'false'
        with:
          node-version: "15.8.x"
      - name: Install package dependencies
        if: steps.cache.outputs.cache-hit == 'false'
        run: yarn install --frozen-lockfile

  compile:
    if: success()
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: "15.8.x"
      - run: yarn && yarn compile

  lint:
    if: success()
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: "15.8.x"
      - run: yarn && yarn lint

  test:
    if: success()
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: "15.8.x"
      - run: yarn && yarn test --ci
